name: GitHub Pages
run-name: ${{ github.actor }} is rolling out a new version of the app üöÄ
on: [push]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # –°–±–æ—Ä–∫–∞ –∏ –¥–µ–ø–ª–æ–π –ø–µ—Ä–≤–æ–≥–æ —Å–∞–π—Ç–∞
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm deps
        working-directory: ./react-chat
        run: npm i
      - name: Build app
        working-directory: ./react-chat
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react-chat/dist
          destination_dir: react-chat

        # –°–±–æ—Ä–∫–∞ –∏ –¥–µ–ø–ª–æ–π –≤—Ç–æ—Ä–æ–≥–æ —Å–∞–π—Ç–∞
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm deps (exam - translate widget)
        working-directory: ./exam
        run: npm i
      - name: Build app (exam - translate widget)
        working-directory: ./exam
        run: npm run build
      - name: exam - translate widget
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exam/dist
          destination_dir: exam
